### ISSUE TITLE
not compatible with current spheres/gambit/ffi

### ISSUE THREAD

**Issue by snifel0** [fourthbit/sphere-cairo#1]
This package tries to import "(spheres/gambit/ffi ffi-simple)" which does not exist!

**Comment by alvatar** [comment]
Thank you @snifel0!
I really have to fix this. I'm currently AFK for some days and I'll get back to the issue ASAP.

**Comment by alvatar** [comment]
Done! Sorry for the delay replying!

**Comment by snifel0** [comment]
Thank you @alvatar!
